[project]
name = "learning-python-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dj-database-url>=3.1.2",
    "django>=6.0.3",
    "django-ninja>=1.5.3",
    "psycopg[binary]>=3.3.3",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "basedpyright>=1.38.2",
    "django-types>=0.23.0",
    "pre-commit>=4.5.1",
    "ruff>=0.15.5",
]

[tool.ruff]
target-version = "py313"
line-length = 100
exclude = ["*/migrations/*"]

[tool.ruff.lint]
select = ["E", "F", "I", "DJ"]

[tool.basedpyright]
pythonVersion = "3.13"
venvPath = "."
venv = ".venv"
exclude = ["**/migrations", ".venv"]
reportUnusedParameter = false
reportImplicitStringConcatenation = false
reportUnannotatedClassAttribute = false
reportAny = false
reportMissingTypeArgument = false
reportIncompatibleVariableOverride = false
