import { match } from "ts-pattern";
import type {
  AvailableProductSchema,
  OutOfStockProductSchema,
  ProductHiddenError,
  ProductNotFoundError,
} from "../generated/types.gen";

// ProductResult is the discriminated union of AvailableProductSchema | OutOfStockProductSchema.
// It is generated by hey-api from the backend's named union type — no manual definition needed.
// The tag field is the discriminant; TypeScript narrows per branch automatically.

// Example 1: match on success variants only.
// stock_count is only accessible when tag is "available" — TypeScript
// narrows the type per branch, so accessing it on the "out_of_stock" branch
// would be a compile error.
function describeProduct(product: AvailableProductSchema | OutOfStockProductSchema): string {
  return match(product)
    .with({ tag: "available" }, (p) => `Available: ${p.name} — ${p.stock_count} in stock at $${p.price}`)
    .with({ tag: "out_of_stock" }, (p) => `Out of stock: ${p.name} at $${p.price}`)
    .exhaustive();
}

// Example 2: match on errors only.
function describeError(error: ProductNotFoundError | ProductHiddenError): string {
  return match(error)
    .with({ tag: "product_not_found" }, (e) => `Product ${e.id} not found: ${e.detail}`)
    .with({ tag: "product_hidden" }, (e) => `Product ${e.id} is restricted: ${e.detail}`)
    .exhaustive();
}

// Example 3: combined success + error match in one exhaustive chain.
// Demonstrates the realistic usage pattern after calling productsApiGetProduct().
// Remove any .with(...) arm to see the TypeScript compile error from .exhaustive().
function handleProductResult(
  result: AvailableProductSchema | OutOfStockProductSchema | ProductNotFoundError | ProductHiddenError
): string {
  return match(result)
    .with({ tag: "available" }, (p) => `Available: ${p.name} (${p.stock_count} left)`)
    .with({ tag: "out_of_stock" }, (p) => `Sold out: ${p.name}`)
    .with({ tag: "product_not_found" }, (e) => `Not found: product ${e.id}`)
    .with({ tag: "product_hidden" }, (e) => `Restricted: product ${e.id}`)
    .exhaustive();
}

// Auth setup example: configure the hey-api client with a Bearer token
// before making authenticated requests to the products endpoints.
//
// import { client } from "../generated";
// client.setConfig({ headers: { Authorization: `Bearer ${token}` } });
